// <auto-generated />
namespace CYBInfracstructure.DataStructure.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class new1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(new1));
        
        string IMigrationMetadata.Id
        {
            get { return "201812131301064_new1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
